import { existsSync, writeFileSync } from 'node:fs';
import { askYesNo, printStep, printSuccess, printWarning, printInfo } from '../prompts.js';
import { SPECIALIST_TEMPLATES, ROUTER_CATEGORIES } from '../defaults.js';
import type { OllamaStepResult } from './ollama.js';
import type { ModelsStepResult } from './models.js';
import type { ChannelsStepResult } from './channels.js';
import type { ServicesStepResult } from './services.js';

export interface GenerateStepResult {
  envPath: string;
  configPath: string;
}

interface WizardState {
  ollama: OllamaStepResult;
  models: ModelsStepResult;
  channels: ChannelsStepResult;
  services: ServicesStepResult;
}

function buildEnv(state: WizardState): string {
  const lines: string[] = ['# Generated by LocalClaw setup wizard', ''];

  // Ollama
  lines.push('# Ollama');
  lines.push(`OLLAMA_URL=${state.ollama.url}`);
  lines.push('');

  // Discord
  if (state.channels.discord.enabled && state.channels.discord.token) {
    lines.push('# Discord');
    lines.push(`DISCORD_BOT_TOKEN=${state.channels.discord.token}`);
    lines.push('');
  }

  // Telegram
  if (state.channels.telegram.enabled && state.channels.telegram.token) {
    lines.push('# Telegram');
    lines.push(`TELEGRAM_BOT_TOKEN=${state.channels.telegram.token}`);
    lines.push('');
  }

  // Slack
  if (state.channels.slack.enabled) {
    lines.push('# Slack (Socket Mode)');
    if (state.channels.slack.token) lines.push(`SLACK_BOT_TOKEN=${state.channels.slack.token}`);
    if (state.channels.slack.appToken) lines.push(`SLACK_APP_TOKEN=${state.channels.slack.appToken}`);
    lines.push('');
  }

  // Web search API key
  if (state.services.webSearch.enabled && state.services.webSearch.apiKey) {
    const provider = state.services.webSearch.provider ?? 'brave';
    const envVar = `${provider.toUpperCase()}_API_KEY`;
    lines.push('# Web Search');
    lines.push(`${envVar}=${state.services.webSearch.apiKey}`);
    lines.push('');
  }

  // TTS
  if (state.services.tts.enabled && state.services.tts.url) {
    lines.push('# TTS');
    lines.push(`QWEN_TTS_URL=${state.services.tts.url}`);
    lines.push('');
  }

  // STT
  if (state.services.stt.enabled && state.services.stt.url) {
    lines.push('# STT');
    lines.push(`WHISPER_URL=${state.services.stt.url}`);
    lines.push('');
  }

  // Image generation
  if (state.services.imageGen.enabled && state.services.imageGen.url) {
    lines.push('# Image Generation');
    lines.push(`IMAGE_GEN_URL=${state.services.imageGen.url}`);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Determine which specialist categories to include based on enabled services.
 */
function getEnabledCategories(state: WizardState): Set<string> {
  const enabled = new Set(['chat', 'memory', 'exec', 'task', 'multi', 'cron', 'config']);

  if (state.services.webSearch.enabled || state.services.browser.enabled) {
    enabled.add('web_search');
    enabled.add('website');
    enabled.add('research');
  }

  const hasChannels = state.channels.discord.enabled
    || state.channels.telegram.enabled
    || state.channels.slack.enabled
    || state.channels.whatsapp.enabled;
  if (hasChannels) {
    enabled.add('message');
  }

  if (state.services.imageGen.enabled) {
    enabled.add('image');
  }

  if (state.services.openCode.enabled) {
    enabled.add('code_gen');
  }

  // personal always available (tools gate on ownerId at runtime)
  enabled.add('personal');

  return enabled;
}

function buildConfig(state: WizardState): string {
  const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const defaultModel = state.models.specialistModel;
  const enabledCategories = getEnabledCategories(state);

  // Owner ID
  const ownerIdLine = state.channels.ownerId
    ? `  ownerId: "${state.channels.ownerId}",`
    : `  // ownerId: "your-user-id",  // Set this to gate owner-only tools (gmail, calendar)`;

  // Build specialists block
  const specialistLines: string[] = [];
  for (const [category, template] of Object.entries(SPECIALIST_TEMPLATES)) {
    if (!enabledCategories.has(category)) continue;
    const model = state.models.categoryModels[category] ?? defaultModel;
    const sp = template.systemPrompt
      ? `\n      systemPrompt: ${JSON.stringify(template.systemPrompt)},`
      : '';
    const toolsStr = template.tools.length
      ? `[${template.tools.map(t => `"${t}"`).join(', ')}]`
      : '[]';
    const pipelineLine = template.pipeline
      ? `\n      pipeline: "${template.pipeline}",`
      : '';

    specialistLines.push(`    ${category}: {
      model: "${model}",${sp}
      maxTokens: ${template.maxTokens},
      temperature: ${template.temperature},
      maxIterations: ${template.maxIterations},
      tools: ${toolsStr},${pipelineLine}
    },`);
  }

  // Build router categories block
  const categoryLines: string[] = [];
  for (const [name, cat] of Object.entries(ROUTER_CATEGORIES)) {
    if (!enabledCategories.has(name)) continue;
    categoryLines.push(`      ${name}: { description: "${cat.description}" },`);
  }

  // Build channels block with security
  const channelLines: string[] = [];
  const channelEntries: Array<{ name: string; result: { enabled: boolean; token?: string; appToken?: string; port?: number } }> = [
    { name: 'discord', result: state.channels.discord },
    { name: 'telegram', result: state.channels.telegram },
    { name: 'slack', result: state.channels.slack },
    { name: 'whatsapp', result: state.channels.whatsapp },
    { name: 'web', result: state.channels.web },
  ];

  for (const ch of channelEntries) {
    if (!ch.result.enabled) {
      channelLines.push(`    ${ch.name}: { enabled: false },`);
      continue;
    }

    const parts: string[] = [`      enabled: true,`];

    // Token
    if (ch.name === 'discord' && ch.result.token) parts.push(`      token: "\${DISCORD_BOT_TOKEN}",`);
    if (ch.name === 'telegram' && ch.result.token) parts.push(`      token: "\${TELEGRAM_BOT_TOKEN}",`);
    if (ch.name === 'slack') {
      if (ch.result.token) parts.push(`      token: "\${SLACK_BOT_TOKEN}",`);
      if (ch.result.appToken) parts.push(`      appToken: "\${SLACK_APP_TOKEN}",`);
    }
    if (ch.name === 'web' && ch.result.port) parts.push(`      port: ${ch.result.port},`);

    // Security block
    const trusted = state.channels.trustedUsers[ch.name];
    if (trusted && trusted.length > 0) {
      parts.push(`      security: {`);
      parts.push(`        trustedUsers: [${trusted.map(id => `"${id}"`).join(', ')}],`);
      parts.push(`        restrictedCategories: ["exec", "config", "personal"],`);
      if (state.channels.ownerId) {
        parts.push(`        ownerOnlyTools: ["gmail_search", "gmail_read", "calendar_list", "calendar_search"],`);
      }
      parts.push(`      },`);
    }

    channelLines.push(`    ${ch.name}: {\n${parts.join('\n')}\n    },`);
  }

  // Web search config
  let webSearchBlock = '';
  if (state.services.webSearch.enabled) {
    const provider = state.services.webSearch.provider ?? 'brave';
    const envVar = `${provider.toUpperCase()}_API_KEY`;
    webSearchBlock = `
      search: {
        provider: "${provider}",
        apiKey: "\${${envVar}}",
      },`;
  }

  // Exec block
  const execSecurity = state.services.exec.security;
  const execBlock = `    exec: {
      security: "${execSecurity}",
      allowlist: ["ls", "cat", "python3", "node", "git"],
      timeout: 30000,
    },`;

  // TTS block
  let ttsBlock = `  tts: { enabled: false },`;
  if (state.services.tts.enabled) {
    ttsBlock = `  tts: {
    enabled: true,
    url: "\${QWEN_TTS_URL}",
    voice: "serena",
    format: "opus",
  },`;
  }

  // STT block
  let sttBlock = `  stt: { enabled: false },`;
  if (state.services.stt.enabled) {
    sttBlock = `  stt: {
    enabled: true,
    url: "\${WHISPER_URL}",
    model: "whisper-large-v3",
    language: "en",
  },`;
  }

  // Vision block
  let visionBlock = `  vision: { enabled: false },`;
  if (state.services.vision.enabled) {
    const vModel = state.services.vision.model ?? 'qwen3-vl:8b';
    visionBlock = `  vision: {
    enabled: true,
    model: "${vModel}",
    prompt: "Describe this image in detail. Include text content, visual elements, layout, and any relevant context. /no_think",
    maxTokens: 1024,
  },`;
  }

  // Browser block
  let browserBlock = `  browser: { enabled: false },`;
  if (state.services.browser.enabled) {
    browserBlock = `  browser: {
    enabled: true,
    headless: ${state.services.browser.headless},
  },`;
  }

  // Heartbeat block
  let heartbeatBlock = `  heartbeat: { enabled: false },`;
  if (state.services.heartbeat.enabled && state.services.heartbeat.channel) {
    heartbeatBlock = `  heartbeat: {
    enabled: true,
    schedule: "0 */2 * * *",
    model: "${state.models.backgroundModel}",
    delivery: {
      channel: "${state.services.heartbeat.channel}",
      target: "${state.services.heartbeat.target ?? ''}",
    },
  },`;
  }

  // Inference backends (OpenAI-compatible, e.g. vLLM) + briefing model
  const inferenceBlock = state.models.inferenceBackends.length
    ? `  inference: {
    backends: [
${state.models.inferenceBackends.map(b => `      { url: "${b.url}", models: [${b.models.map(m => `"${m}"`).join(', ')}] },`).join('\n')}
    ],
  },
`
    : '';
  const briefingBlock = `  briefing: { model: "${state.models.backgroundModel}" },`;

  // Reasoning block
  let reasoningBlock = '';
  if (state.services.reasoning.enabled && state.services.reasoning.model) {
    reasoningBlock = `
  reasoning: {
    model: "${state.services.reasoning.model}",
    maxTokens: 8192,
    temperature: 0.6,
  },`;
  }

  // Image gen block
  let imageGenBlock = '';
  if (state.services.imageGen.enabled) {
    imageGenBlock = `
  imageGen: {
    enabled: true,
    url: "\${IMAGE_GEN_URL}",
    model: "${state.services.imageGen.model ?? 'flux2-klein:4b-fp8'}",
  },`;
  }

  // OpenCode block
  let openCodeBlock = '';
  if (state.services.openCode.enabled) {
    openCodeBlock = `
  openCode: {
    enabled: true,
    port: ${state.services.openCode.port ?? 3500},
    defaultModel: "ollama/${defaultModel}",
  },`;
  }

  // Voice block
  let voiceBlock = '';
  if (state.services.tts.enabled) {
    voiceBlock = `
  voice: {
    model: "${state.models.routerModel}",  // fast model for voice-originated messages
  },`;
  }

  // Memory block
  const memoryBlock = `  memory: {
    backend: "markdown",
    extractionModel: "${defaultModel}",
    consolidation: {
      enabled: true,
      model: "${state.models.routerModel}",
      similarityThreshold: 0.85,
    },
  },`;

  return `{
  // LocalClaw Configuration
  // Generated by setup wizard

${ownerIdLine}
  timezone: "${tz}",

  ollama: {
    url: "\${OLLAMA_URL}",
    keepAlive: "30m",
  },

${inferenceBlock}${briefingBlock}

  router: {
    model: "${state.models.routerModel}",
    timeout: 2000,
    defaultCategory: "chat",
    categories: {
${categoryLines.join('\n')}
    },
  },

  specialists: {
${specialistLines.join('\n')}
  },

  channels: {
${channelLines.join('\n')}
  },

  agents: {
    default: "main",
    list: [
      { id: "main", name: "LocalClaw Assistant" },
    ],
    bindings: [],
  },

${memoryBlock}

  cron: { enabled: true, store: "data/cron.json" },

  session: {
    transcriptDir: "data/sessions",
    maxHistoryTurns: 100,
    contextSize: 32768,
    recentTurnsToKeep: 6,
    summarizeToolObservations: true,
  },

  tools: {
    web: {${webSearchBlock}
      fetch: { maxChars: 30000 },
    },
${execBlock}
  },

  ${heartbeatBlock}

  ${browserBlock}

  ${ttsBlock}

  ${sttBlock}

  ${visionBlock}${reasoningBlock}${imageGenBlock}${openCodeBlock}${voiceBlock}
}
`;
}

export async function runGenerateStep(state: WizardState): Promise<GenerateStepResult> {
  printStep(6, 7, 'Generate Configuration');

  const envContent = buildEnv(state);
  const configContent = buildConfig(state);

  let envPath = '.env';
  let configPath = 'localclaw.config.json5';

  // Check for existing files
  if (existsSync(envPath)) {
    printWarning('.env already exists');
    const overwrite = await askYesNo('Overwrite .env?', false);
    if (!overwrite) {
      envPath = '.env.setup';
      printInfo(`Writing to ${envPath} instead`);
    }
  }

  if (existsSync(configPath)) {
    printWarning('localclaw.config.json5 already exists');
    const overwrite = await askYesNo('Overwrite localclaw.config.json5?', false);
    if (!overwrite) {
      configPath = 'localclaw.config.json5.setup';
      printInfo(`Writing to ${configPath} instead`);
    }
  }

  writeFileSync(envPath, envContent, 'utf-8');
  printSuccess(`Written: ${envPath}`);

  writeFileSync(configPath, configContent, 'utf-8');
  printSuccess(`Written: ${configPath}`);

  return { envPath, configPath };
}
