import { existsSync, writeFileSync } from 'node:fs';
import { askYesNo, printStep, printSuccess, printWarning, printInfo } from '../prompts.js';
import { SPECIALIST_TEMPLATES, ROUTER_CATEGORIES } from '../defaults.js';
import type { OllamaStepResult } from './ollama.js';
import type { ModelsStepResult } from './models.js';
import type { ChannelsStepResult } from './channels.js';
import type { ServicesStepResult } from './services.js';

export interface GenerateStepResult {
  envPath: string;
  configPath: string;
}

interface WizardState {
  ollama: OllamaStepResult;
  models: ModelsStepResult;
  channels: ChannelsStepResult;
  services: ServicesStepResult;
}

function buildEnv(state: WizardState): string {
  const lines: string[] = ['# Generated by LocalClaw setup wizard', ''];

  // Ollama
  lines.push('# Ollama');
  lines.push(`OLLAMA_URL=${state.ollama.url}`);
  lines.push('');

  // Discord
  if (state.channels.discord.enabled && state.channels.discord.token) {
    lines.push('# Discord');
    lines.push(`DISCORD_BOT_TOKEN=${state.channels.discord.token}`);
    lines.push('');
  }

  // Telegram
  if (state.channels.telegram.enabled && state.channels.telegram.token) {
    lines.push('# Telegram');
    lines.push(`TELEGRAM_BOT_TOKEN=${state.channels.telegram.token}`);
    lines.push('');
  }

  // Slack
  if (state.channels.slack.enabled) {
    lines.push('# Slack (Socket Mode)');
    if (state.channels.slack.token) lines.push(`SLACK_BOT_TOKEN=${state.channels.slack.token}`);
    if (state.channels.slack.appToken) lines.push(`SLACK_APP_TOKEN=${state.channels.slack.appToken}`);
    lines.push('');
  }

  // Web search API key
  if (state.services.webSearch.enabled && state.services.webSearch.apiKey) {
    const provider = state.services.webSearch.provider ?? 'brave';
    const envVar = `${provider.toUpperCase()}_API_KEY`;
    lines.push('# Web Search');
    lines.push(`${envVar}=${state.services.webSearch.apiKey}`);
    lines.push('');
  }

  // TTS
  if (state.services.tts.enabled && state.services.tts.url) {
    lines.push('# TTS');
    lines.push(`QWEN_TTS_URL=${state.services.tts.url}`);
    lines.push('');
  }

  // STT
  if (state.services.stt.enabled && state.services.stt.url) {
    lines.push('# STT');
    lines.push(`WHISPER_URL=${state.services.stt.url}`);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Determine which specialist categories to include based on enabled services.
 * Core categories are always included; others depend on what the user enabled.
 */
function getEnabledCategories(state: WizardState): Set<string> {
  const enabled = new Set(['chat', 'memory', 'exec', 'task', 'multi']);

  if (state.services.webSearch.enabled || state.services.browser.enabled) {
    enabled.add('web_search');
  }

  const hasChannels = state.channels.discord.enabled
    || state.channels.telegram.enabled
    || state.channels.slack.enabled
    || state.channels.whatsapp.enabled;
  if (hasChannels) {
    enabled.add('message');
  }

  // cron, config, website — always useful if exec is available
  enabled.add('cron');
  enabled.add('config');

  return enabled;
}

function buildConfig(state: WizardState): string {
  const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const defaultModel = state.models.specialistModel;
  const enabledCategories = getEnabledCategories(state);

  // Build specialists block — only for enabled categories
  const specialistLines: string[] = [];
  for (const [category, template] of Object.entries(SPECIALIST_TEMPLATES)) {
    if (!enabledCategories.has(category)) continue;
    const model = state.models.categoryModels[category] ?? defaultModel;
    const sp = template.systemPrompt
      ? `\n      systemPrompt: ${JSON.stringify(template.systemPrompt)},`
      : '';
    const toolsStr = template.tools.length
      ? `[${template.tools.map(t => `"${t}"`).join(', ')}]`
      : '[]';

    specialistLines.push(`    ${category}: {
      model: "${model}",${sp}
      maxTokens: ${template.maxTokens},
      temperature: ${template.temperature},
      maxIterations: ${template.maxIterations},
      tools: ${toolsStr},
    },`);
  }

  // Build router categories block — only for enabled categories
  const categoryLines: string[] = [];
  for (const [name, cat] of Object.entries(ROUTER_CATEGORIES)) {
    if (!enabledCategories.has(name)) continue;
    categoryLines.push(`      ${name}: { description: "${cat.description}" },`);
  }

  // Build channels block
  const channelLines: string[] = [];

  // Discord
  if (state.channels.discord.enabled) {
    channelLines.push(`    discord: {
      enabled: true,
      token: "\${DISCORD_BOT_TOKEN}",
    },`);
  } else {
    channelLines.push(`    discord: { enabled: false },`);
  }

  // Telegram
  if (state.channels.telegram.enabled) {
    channelLines.push(`    telegram: {
      enabled: true,
      token: "\${TELEGRAM_BOT_TOKEN}",
    },`);
  } else {
    channelLines.push(`    telegram: { enabled: false },`);
  }

  // Slack
  if (state.channels.slack.enabled) {
    channelLines.push(`    slack: {
      enabled: true,
      token: "\${SLACK_BOT_TOKEN}",
      appToken: "\${SLACK_APP_TOKEN}",
    },`);
  } else {
    channelLines.push(`    slack: { enabled: false },`);
  }

  // WhatsApp
  if (state.channels.whatsapp.enabled) {
    channelLines.push(`    whatsapp: {
      enabled: true,
    },`);
  } else {
    channelLines.push(`    whatsapp: { enabled: false },`);
  }

  // Web
  if (state.channels.web.enabled) {
    const port = state.channels.web.port ?? 3100;
    channelLines.push(`    web: {
      enabled: true,
      port: ${port},
    },`);
  } else {
    channelLines.push(`    web: { enabled: false },`);
  }

  // Build web search config
  let webSearchBlock = '';
  if (state.services.webSearch.enabled) {
    const provider = state.services.webSearch.provider ?? 'brave';
    const envVar = `${provider.toUpperCase()}_API_KEY`;
    webSearchBlock = `
      search: {
        provider: "${provider}",
        apiKey: "\${${envVar}}",
      },`;
  }

  // Build exec block
  const execSecurity = state.services.exec.security;
  const execBlock = `    exec: {
      security: "${execSecurity}",
      allowlist: ["ls", "cat", "python3", "node", "git"],
      timeout: 30000,
    },`;

  // Build TTS block
  let ttsBlock = `  tts: { enabled: false },`;
  if (state.services.tts.enabled) {
    ttsBlock = `  tts: {
    enabled: true,
    url: "\${QWEN_TTS_URL}",
    voice: "serena",
    format: "opus",
  },`;
  }

  // Build STT block
  let sttBlock = `  stt: { enabled: false },`;
  if (state.services.stt.enabled) {
    sttBlock = `  stt: {
    enabled: true,
    url: "\${WHISPER_URL}",
    model: "whisper-large-v3",
    language: "en",
  },`;
  }

  // Build vision block
  let visionBlock = `  vision: { enabled: false },`;
  if (state.services.vision.enabled) {
    const vModel = state.services.vision.model ?? 'qwen3-vl:8b';
    visionBlock = `  vision: {
    enabled: true,
    model: "${vModel}",
    prompt: "Describe this image in detail. Include text content, visual elements, layout, and any relevant context.",
    maxTokens: 1024,
  },`;
  }

  // Build browser block
  let browserBlock = `  browser: { enabled: false },`;
  if (state.services.browser.enabled) {
    browserBlock = `  browser: {
    enabled: true,
    headless: ${state.services.browser.headless},
  },`;
  }

  return `{
  // LocalClaw Configuration
  // Generated by setup wizard

  timezone: "${tz}",

  ollama: {
    url: "\${OLLAMA_URL}",
    keepAlive: "30m",
  },

  router: {
    model: "${state.models.routerModel}",
    timeout: 2000,
    defaultCategory: "chat",
    categories: {
${categoryLines.join('\n')}
    },
  },

  specialists: {
${specialistLines.join('\n')}
  },

  channels: {
${channelLines.join('\n')}
  },

  agents: {
    default: "main",
    list: [
      { id: "main", name: "LocalClaw Assistant" },
    ],
    bindings: [],
  },

  memory: {
    backend: "markdown",
  },

  cron: { enabled: false },

  session: {
    transcriptDir: "data/sessions",
    maxHistoryTurns: 100,
    contextSize: 32768,
    recentTurnsToKeep: 6,
  },

  tools: {
    web: {${webSearchBlock}
      fetch: { maxChars: 30000 },
    },
${execBlock}
  },

  ${browserBlock}

  ${ttsBlock}

  ${sttBlock}

  ${visionBlock}
}
`;
}

export async function runGenerateStep(state: WizardState): Promise<GenerateStepResult> {
  printStep(6, 7, 'Generate Configuration');

  const envContent = buildEnv(state);
  const configContent = buildConfig(state);

  let envPath = '.env';
  let configPath = 'localclaw.config.json5';

  // Check for existing files
  if (existsSync(envPath)) {
    printWarning('.env already exists');
    const overwrite = await askYesNo('Overwrite .env?', false);
    if (!overwrite) {
      envPath = '.env.setup';
      printInfo(`Writing to ${envPath} instead`);
    }
  }

  if (existsSync(configPath)) {
    printWarning('localclaw.config.json5 already exists');
    const overwrite = await askYesNo('Overwrite localclaw.config.json5?', false);
    if (!overwrite) {
      configPath = 'localclaw.config.json5.setup';
      printInfo(`Writing to ${configPath} instead`);
    }
  }

  writeFileSync(envPath, envContent, 'utf-8');
  printSuccess(`Written: ${envPath}`);

  writeFileSync(configPath, configContent, 'utf-8');
  printSuccess(`Written: ${configPath}`);

  return { envPath, configPath };
}
