/**
 * HTML templates for professional document generation.
 * Used by the document tool to wrap model-generated content in
 * well-formatted layouts before LibreOffice conversion.
 */

export interface DocumentContent {
  title: string;
  subtitle?: string;
  author?: string;
  date?: string;
  sections: Array<{ heading: string; content: string }>;
  metadata?: Record<string, string>;
}

const SHARED_CSS = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; color: #1a1a1a; line-height: 1.6; padding: 40px 60px; max-width: 800px; margin: 0 auto; }
  h1 { font-size: 28px; font-weight: 700; color: #0d1b2a; margin-bottom: 8px; }
  h2 { font-size: 20px; font-weight: 600; color: #1b263b; margin-top: 28px; margin-bottom: 12px; border-bottom: 2px solid #e0e0e0; padding-bottom: 6px; }
  h3 { font-size: 16px; font-weight: 600; color: #415a77; margin-top: 20px; margin-bottom: 8px; }
  p { margin-bottom: 12px; font-size: 14px; }
  ul, ol { margin: 8px 0 16px 24px; font-size: 14px; }
  li { margin-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px; }
  th { background: #f0f0f0; font-weight: 600; text-align: left; padding: 8px 12px; border: 1px solid #ddd; }
  td { padding: 8px 12px; border: 1px solid #ddd; }
  tr:nth-child(even) { background: #fafafa; }
  .subtitle { font-size: 16px; color: #666; margin-bottom: 24px; }
  .meta { font-size: 12px; color: #888; margin-bottom: 32px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e0e0e0; font-size: 11px; color: #999; }
`;

export function renderTemplate(template: string, content: DocumentContent): string {
  switch (template) {
    case 'report': return renderReport(content);
    case 'memo': return renderMemo(content);
    case 'invoice': return renderInvoice(content);
    case 'letter': return renderLetter(content);
    default: return renderSimple(content);
  }
}

function renderReport(c: DocumentContent): string {
  const sections = c.sections.map((s, i) => `
    <h2>${i + 1}. ${s.heading}</h2>
    ${s.content}
  `).join('\n');

  return `<!DOCTYPE html><html><head><style>${SHARED_CSS}
    .cover { text-align: center; padding: 120px 0 60px; }
    .cover h1 { font-size: 36px; margin-bottom: 16px; }
  </style></head><body>
    <div class="cover">
      <h1>${c.title}</h1>
      ${c.subtitle ? `<p class="subtitle">${c.subtitle}</p>` : ''}
      <p class="meta">${c.author ? `Prepared by ${c.author}` : ''}${c.date ? ` | ${c.date}` : ''}</p>
    </div>
    ${sections}
    <div class="footer">Generated by LocalClaw</div>
  </body></html>`;
}

function renderMemo(c: DocumentContent): string {
  const body = c.sections.map(s => `<h3>${s.heading}</h3>${s.content}`).join('\n');

  return `<!DOCTYPE html><html><head><style>${SHARED_CSS}
    .memo-header { background: #f5f5f5; padding: 16px 20px; margin-bottom: 24px; border-left: 4px solid #0d1b2a; }
    .memo-field { font-size: 14px; margin: 4px 0; }
    .memo-field strong { display: inline-block; width: 80px; }
  </style></head><body>
    <h1>Memorandum</h1>
    <div class="memo-header">
      ${c.metadata?.to ? `<p class="memo-field"><strong>To:</strong> ${c.metadata.to}</p>` : ''}
      ${c.metadata?.from ? `<p class="memo-field"><strong>From:</strong> ${c.metadata.from}</p>` : ''}
      <p class="memo-field"><strong>Date:</strong> ${c.date ?? new Date().toLocaleDateString()}</p>
      <p class="memo-field"><strong>Subject:</strong> ${c.title}</p>
    </div>
    ${body}
    <div class="footer">Generated by LocalClaw</div>
  </body></html>`;
}

function renderInvoice(c: DocumentContent): string {
  const body = c.sections.map(s => `<h3>${s.heading}</h3>${s.content}`).join('\n');

  return `<!DOCTYPE html><html><head><style>${SHARED_CSS}
    .invoice-header { display: flex; justify-content: space-between; margin-bottom: 32px; }
    .invoice-number { font-size: 24px; color: #0d1b2a; }
    .total-row { font-weight: 700; background: #e8f4e8 !important; }
  </style></head><body>
    <div class="invoice-header">
      <div>
        <h1>${c.title}</h1>
        ${c.subtitle ? `<p class="subtitle">${c.subtitle}</p>` : ''}
      </div>
      <div style="text-align: right;">
        <p class="meta">${c.date ?? new Date().toLocaleDateString()}</p>
        ${c.metadata?.invoiceNumber ? `<p class="invoice-number">#${c.metadata.invoiceNumber}</p>` : ''}
      </div>
    </div>
    ${body}
    <div class="footer">Generated by LocalClaw</div>
  </body></html>`;
}

function renderLetter(c: DocumentContent): string {
  const body = c.sections.map(s => s.content).join('\n\n');

  return `<!DOCTYPE html><html><head><style>${SHARED_CSS}
    .letter-date { text-align: right; margin-bottom: 32px; }
    .addressee { margin-bottom: 24px; }
    .signature { margin-top: 48px; }
  </style></head><body>
    <p class="letter-date">${c.date ?? new Date().toLocaleDateString()}</p>
    ${c.metadata?.to ? `<div class="addressee"><p>${c.metadata.to}</p></div>` : ''}
    <p><strong>${c.title}</strong></p>
    <br/>
    ${body}
    <div class="signature">
      <p>Sincerely,</p>
      <br/><br/>
      ${c.author ? `<p>${c.author}</p>` : ''}
    </div>
  </body></html>`;
}

function renderSimple(c: DocumentContent): string {
  const sections = c.sections.map(s => `<h2>${s.heading}</h2>${s.content}`).join('\n');

  return `<!DOCTYPE html><html><head><style>${SHARED_CSS}</style></head><body>
    <h1>${c.title}</h1>
    ${c.subtitle ? `<p class="subtitle">${c.subtitle}</p>` : ''}
    ${sections}
  </body></html>`;
}

export const AVAILABLE_TEMPLATES = ['report', 'memo', 'invoice', 'letter', 'simple'] as const;
export type TemplateName = typeof AVAILABLE_TEMPLATES[number];
